-- CR-Workout v9.8.9 – TIF Viking Off Season
-- Seks programmer. Sett = runde.
-- Kjør hele scriptet én gang i Supabase SQL Editor.

insert into public.cr_programs
(id,name,description,icon,active,sort_order)
values
('tif_offseason_1_v1','TIF Viking – Økt 1 Underkropp variant 1','TIF Viking – Off Season','🏐',true,200),
('tif_offseason_1_v2','TIF Viking – Økt 1 Underkropp variant 2','TIF Viking – Off Season','🏐',true,210),
('tif_offseason_2_v1','TIF Viking – Økt 2 Overkropp variant 1','TIF Viking – Off Season','🏐',true,220),
('tif_offseason_2_v2','TIF Viking – Økt 2 Overkropp variant 2','TIF Viking – Off Season','🏐',true,230),
('tif_offseason_3_v1','TIF Viking – Økt 3 Split Over/underkropp variant 1','TIF Viking – Off Season','🏐',true,240),
('tif_offseason_3_v2','TIF Viking – Økt 3 Split Over/underkropp variant 2','TIF Viking – Off Season','🏐',true,250)
on conflict (id) do update set
 name=excluded.name,description=excluded.description,icon=excluded.icon,active=true,sort_order=excluded.sort_order;

delete from public.cr_program_activities where program_id in ('tif_offseason_1_v1','tif_offseason_1_v2','tif_offseason_2_v1','tif_offseason_2_v2','tif_offseason_3_v1','tif_offseason_3_v2');

insert into public.cr_program_activities
(program_id,group_name,order_no,round_no,activity,reps,load,description)
values
('tif_offseason_1_v1','Main',1,1,'CMJ','2 hopp','','Runde 1 · Maks høyde, kort kontakttid'),
('tif_offseason_1_v1','Main',2,1,'Knebøy','4 reps 80–85 % @ 1-2 RIR','','Runde 1 · Rolig ned, tempo opp'),
('tif_offseason_1_v1','Main',3,1,'Bulgarsk splittbøy','6 reps per fot (2 RIR)','','Runde 1 · Bryst opp, lavt kne'),
('tif_offseason_1_v1','Main',4,1,'Rumensk markløft / leg curl','5 reps (2 RIR)','','Runde 1 · Kontrollert'),
('tif_offseason_1_v1','Main',5,1,'KB goblet squat','5 reps (2 RIR)','','Runde 1 · Kontrollert'),
('tif_offseason_1_v1','Main',6,1,'Et fots tåhev','8 reps per fot (2 RIR)','','Runde 1 · Kontrollert (ROM)'),
('tif_offseason_1_v1','Main',7,1,'Depth Landing','3 reps','','Runde 1 · Stabil landing'),
('tif_offseason_1_v1','Main',8,2,'CMJ','2 hopp','','Runde 2 · Maks høyde, kort kontakttid'),
('tif_offseason_1_v1','Main',9,2,'Knebøy','4 reps 80–85 % @ 1-2 RIR','','Runde 2 · Rolig ned, tempo opp'),
('tif_offseason_1_v1','Main',10,2,'Bulgarsk splittbøy','6 reps per fot (2 RIR)','','Runde 2 · Bryst opp, lavt kne'),
('tif_offseason_1_v1','Main',11,2,'Rumensk markløft / leg curl','5 reps (2 RIR)','','Runde 2 · Kontrollert'),
('tif_offseason_1_v1','Main',12,2,'KB goblet squat','5 reps (2 RIR)','','Runde 2 · Kontrollert'),
('tif_offseason_1_v1','Main',13,2,'Et fots tåhev','8 reps per fot (2 RIR)','','Runde 2 · Kontrollert (ROM)'),
('tif_offseason_1_v1','Main',14,2,'Depth Landing','3 reps','','Runde 2 · Stabil landing'),
('tif_offseason_1_v1','Main',15,3,'CMJ','2 hopp','','Runde 3 · Maks høyde, kort kontakttid'),
('tif_offseason_1_v1','Main',16,3,'Knebøy','4 reps 80–85 % @ 1-2 RIR','','Runde 3 · Rolig ned, tempo opp'),
('tif_offseason_1_v1','Main',17,3,'Bulgarsk splittbøy','6 reps per fot (2 RIR)','','Runde 3 · Bryst opp, lavt kne'),
('tif_offseason_1_v1','Main',18,3,'Rumensk markløft / leg curl','5 reps (2 RIR)','','Runde 3 · Kontrollert'),
('tif_offseason_1_v1','Main',19,3,'KB goblet squat','5 reps (2 RIR)','','Runde 3 · Kontrollert'),
('tif_offseason_1_v1','Main',20,3,'Et fots tåhev','8 reps per fot (2 RIR)','','Runde 3 · Kontrollert (ROM)'),
('tif_offseason_1_v1','Main',21,3,'Depth Landing','3 reps','','Runde 3 · Stabil landing'),
('tif_offseason_1_v1','Main',22,4,'Knebøy','4 reps 80–85 % @ 1-2 RIR','','Runde 4 · Rolig ned, tempo opp'),
('tif_offseason_1_v1','Main',23,4,'Bulgarsk splittbøy','6 reps per fot (2 RIR)','','Runde 4 · Bryst opp, lavt kne'),
('tif_offseason_1_v1','Main',24,4,'Rumensk markløft / leg curl','5 reps (2 RIR)','','Runde 4 · Kontrollert'),
('tif_offseason_1_v1','Main',25,4,'KB goblet squat','5 reps (2 RIR)','','Runde 4 · Kontrollert'),
('tif_offseason_1_v2','Main',1,1,'Box jump','2 hopp','','Runde 1 · Maks høyde, kort kontakttid på boks'),
('tif_offseason_1_v2','Main',2,1,'Pogo jumps','15 hopp','','Runde 1 · Kort landing, små hopp'),
('tif_offseason_1_v2','Main',3,1,'Plyo bar squat','6 reps','','Runde 1 · 50–60 % av 1RM knebøy, maksimal hastighet'),
('tif_offseason_1_v2','Main',4,1,'Leg extension','6 reps per fot (2 RIR)','','Runde 1 · Hvis du har tilgang til maskin, utfall om ikke'),
('tif_offseason_1_v2','Main',5,1,'Hip Thrust','4 reps (1-2 RIR)','','Runde 1 · Høyt skyv, maksimal hastighet'),
('tif_offseason_1_v2','Main',6,1,'Nordic / leg curl','10-12 reps per fot','','Runde 1 · Kontrollert bevegelse'),
('tif_offseason_1_v2','Main',7,1,'Depth Landing','3 reps','','Runde 1 · Stabil landing'),
('tif_offseason_1_v2','Main',8,2,'Box jump','2 hopp','','Runde 2 · Maks høyde, kort kontakttid på boks'),
('tif_offseason_1_v2','Main',9,2,'Pogo jumps','15 hopp','','Runde 2 · Kort landing, små hopp'),
('tif_offseason_1_v2','Main',10,2,'Plyo bar squat','6 reps','','Runde 2 · 50–60 % av 1RM knebøy, maksimal hastighet'),
('tif_offseason_1_v2','Main',11,2,'Leg extension','6 reps per fot (2 RIR)','','Runde 2 · Hvis du har tilgang til maskin, utfall om ikke'),
('tif_offseason_1_v2','Main',12,2,'Hip Thrust','4 reps (1-2 RIR)','','Runde 2 · Høyt skyv, maksimal hastighet'),
('tif_offseason_1_v2','Main',13,2,'Nordic / leg curl','10-12 reps per fot','','Runde 2 · Kontrollert bevegelse'),
('tif_offseason_1_v2','Main',14,2,'Depth Landing','3 reps','','Runde 2 · Stabil landing'),
('tif_offseason_1_v2','Main',15,3,'Box jump','2 hopp','','Runde 3 · Maks høyde, kort kontakttid på boks'),
('tif_offseason_1_v2','Main',16,3,'Pogo jumps','15 hopp','','Runde 3 · Kort landing, små hopp'),
('tif_offseason_1_v2','Main',17,3,'Plyo bar squat','6 reps','','Runde 3 · 50–60 % av 1RM knebøy, maksimal hastighet'),
('tif_offseason_1_v2','Main',18,3,'Leg extension','6 reps per fot (2 RIR)','','Runde 3 · Hvis du har tilgang til maskin, utfall om ikke'),
('tif_offseason_1_v2','Main',19,3,'Hip Thrust','4 reps (1-2 RIR)','','Runde 3 · Høyt skyv, maksimal hastighet'),
('tif_offseason_1_v2','Main',20,3,'Nordic / leg curl','10-12 reps per fot','','Runde 3 · Kontrollert bevegelse'),
('tif_offseason_1_v2','Main',21,3,'Depth Landing','3 reps','','Runde 3 · Stabil landing'),
('tif_offseason_1_v2','Main',22,4,'Plyo bar squat','6 reps','','Runde 4 · 50–60 % av 1RM knebøy, maksimal hastighet'),
('tif_offseason_1_v2','Main',23,4,'Leg extension','6 reps per fot (2 RIR)','','Runde 4 · Hvis du har tilgang til maskin, utfall om ikke'),
('tif_offseason_1_v2','Main',24,4,'Hip Thrust','4 reps (1-2 RIR)','','Runde 4 · Høyt skyv, maksimal hastighet'),
('tif_offseason_2_v1','Main',1,1,'Medball Chest Throw','4-6 reps','','Runde 1 · Plyo arbeid, maks kraft ball til vegg'),
('tif_offseason_2_v1','Main',2,1,'BB/DB Benkpress','4 reps 80–85 % · mål 1-2 RIR','','Runde 1 · Rolig ned, tempo opp'),
('tif_offseason_2_v1','Main',3,1,'Pull ups / nedtrekk','6 reps (2 RIR)','','Runde 1 · Full bevegelse'),
('tif_offseason_2_v1','Main',4,1,'En arms roing på benk','8 reps per arm (2 RIR)','','Runde 1 · Kontrollert trekk, skulderblad tilbake'),
('tif_offseason_2_v1','Main',5,1,'Push press','6 reps (2 RIR)','','Runde 1 · Stabil overkropp, press over hodet'),
('tif_offseason_2_v1','Main',6,1,'Sideløft m/db på benk','10-12 reps per arm','','Runde 1 · Lett vekt, kontrollert bevegelse'),
('tif_offseason_2_v1','Main',7,1,'One arm DB carry','20-30 m per arm','','Runde 1 · Tung belastning'),
('tif_offseason_2_v1','Main',8,2,'Medball Chest Throw','4-6 reps','','Runde 2 · Plyo arbeid, maks kraft ball til vegg'),
('tif_offseason_2_v1','Main',9,2,'BB/DB Benkpress','4 reps 80–85 % · mål 1-2 RIR','','Runde 2 · Rolig ned, tempo opp'),
('tif_offseason_2_v1','Main',10,2,'Pull ups / nedtrekk','6 reps (2 RIR)','','Runde 2 · Full bevegelse'),
('tif_offseason_2_v1','Main',11,2,'En arms roing på benk','8 reps per arm (2 RIR)','','Runde 2 · Kontrollert trekk, skulderblad tilbake'),
('tif_offseason_2_v1','Main',12,2,'Push press','6 reps (2 RIR)','','Runde 2 · Stabil overkropp, press over hodet'),
('tif_offseason_2_v1','Main',13,2,'Sideløft m/db på benk','10-12 reps per arm','','Runde 2 · Lett vekt, kontrollert bevegelse'),
('tif_offseason_2_v1','Main',14,2,'One arm DB carry','20-30 m per arm','','Runde 2 · Tung belastning'),
('tif_offseason_2_v1','Main',15,3,'Medball Chest Throw','4-6 reps','','Runde 3 · Plyo arbeid, maks kraft ball til vegg'),
('tif_offseason_2_v1','Main',16,3,'BB/DB Benkpress','4 reps 80–85 % · mål 1-2 RIR','','Runde 3 · Rolig ned, tempo opp'),
('tif_offseason_2_v1','Main',17,3,'Pull ups / nedtrekk','6 reps (2 RIR)','','Runde 3 · Full bevegelse'),
('tif_offseason_2_v1','Main',18,3,'En arms roing på benk','8 reps per arm (2 RIR)','','Runde 3 · Kontrollert trekk, skulderblad tilbake'),
('tif_offseason_2_v1','Main',19,3,'Push press','6 reps (2 RIR)','','Runde 3 · Stabil overkropp, press over hodet'),
('tif_offseason_2_v1','Main',20,3,'Sideløft m/db på benk','10-12 reps per arm','','Runde 3 · Lett vekt, kontrollert bevegelse'),
('tif_offseason_2_v1','Main',21,3,'One arm DB carry','20-30 m per arm','','Runde 3 · Tung belastning'),
('tif_offseason_2_v1','Main',22,4,'BB/DB Benkpress','4 reps 80–85 % · mål 1-2 RIR','','Runde 4 · Rolig ned, tempo opp'),
('tif_offseason_2_v1','Main',23,4,'Pull ups / nedtrekk','6 reps (2 RIR)','','Runde 4 · Full bevegelse'),
('tif_offseason_2_v1','Main',24,4,'En arms roing på benk','8 reps per arm (2 RIR)','','Runde 4 · Kontrollert trekk, skulderblad tilbake'),
('tif_offseason_2_v2','Main',1,1,'Medball Chest Throw','4-6 reps','','Runde 1 · Plyo arbeid, maks kraft ball til vegg'),
('tif_offseason_2_v2','Main',2,1,'BB/DB Skråbenk','4 reps 2-3 RIR','','Runde 1 · Rolig ned, tempo opp, 2 sek hold i bunn'),
('tif_offseason_2_v2','Main',3,1,'Pull ups / nedtrekk','6 reps (2 RIR)','','Runde 1 · Full bevegelse'),
('tif_offseason_2_v2','Main',4,1,'DB Roing på skråbenk','8 reps (2 RIR)','','Runde 1 · Kontrollert trekk, skulderblad tilbake'),
('tif_offseason_2_v2','Main',5,1,'Sideløft m/db','10-12 reps per arm','','Runde 1 · Lett vekt, kontrollert bevegelse'),
('tif_offseason_2_v2','Main',6,1,'Half Kneeling DB Press','8 reps per arm (2 RIR)','','Runde 1 · Stabil overkropp, kontrollert press over hodet'),
('tif_offseason_2_v2','Main',7,1,'Pallof press','10 reps per side','','Runde 1 · Stabil kjerne, unngå rotasjon med overkropp'),
('tif_offseason_2_v2','Main',8,2,'Medball Chest Throw','4-6 reps','','Runde 2 · Plyo arbeid, maks kraft ball til vegg'),
('tif_offseason_2_v2','Main',9,2,'BB/DB Skråbenk','4 reps 2-3 RIR','','Runde 2 · Rolig ned, tempo opp, 2 sek hold i bunn'),
('tif_offseason_2_v2','Main',10,2,'Pull ups / nedtrekk','6 reps (2 RIR)','','Runde 2 · Full bevegelse'),
('tif_offseason_2_v2','Main',11,2,'DB Roing på skråbenk','8 reps (2 RIR)','','Runde 2 · Kontrollert trekk, skulderblad tilbake'),
('tif_offseason_2_v2','Main',12,2,'Sideløft m/db','10-12 reps per arm','','Runde 2 · Lett vekt, kontrollert bevegelse'),
('tif_offseason_2_v2','Main',13,2,'Half Kneeling DB Press','8 reps per arm (2 RIR)','','Runde 2 · Stabil overkropp, kontrollert press over hodet'),
('tif_offseason_2_v2','Main',14,2,'Pallof press','10 reps per side','','Runde 2 · Stabil kjerne, unngå rotasjon med overkropp'),
('tif_offseason_2_v2','Main',15,3,'Medball Chest Throw','4-6 reps','','Runde 3 · Plyo arbeid, maks kraft ball til vegg'),
('tif_offseason_2_v2','Main',16,3,'BB/DB Skråbenk','4 reps 2-3 RIR','','Runde 3 · Rolig ned, tempo opp, 2 sek hold i bunn'),
('tif_offseason_2_v2','Main',17,3,'Pull ups / nedtrekk','6 reps (2 RIR)','','Runde 3 · Full bevegelse'),
('tif_offseason_2_v2','Main',18,3,'DB Roing på skråbenk','8 reps (2 RIR)','','Runde 3 · Kontrollert trekk, skulderblad tilbake'),
('tif_offseason_2_v2','Main',19,3,'Sideløft m/db','10-12 reps per arm','','Runde 3 · Lett vekt, kontrollert bevegelse'),
('tif_offseason_2_v2','Main',20,3,'Half Kneeling DB Press','8 reps per arm (2 RIR)','','Runde 3 · Stabil overkropp, kontrollert press over hodet'),
('tif_offseason_2_v2','Main',21,3,'Pallof press','10 reps per side','','Runde 3 · Stabil kjerne, unngå rotasjon med overkropp'),
('tif_offseason_2_v2','Main',22,4,'BB/DB Skråbenk','4 reps 2-3 RIR','','Runde 4 · Rolig ned, tempo opp, 2 sek hold i bunn'),
('tif_offseason_2_v2','Main',23,4,'DB Roing på skråbenk','8 reps (2 RIR)','','Runde 4 · Kontrollert trekk, skulderblad tilbake'),
('tif_offseason_3_v1','Main',1,1,'Lateral Bound','4 per side','','Runde 1 · Sideveis eksplosivitet'),
('tif_offseason_3_v1','Main',2,1,'Frivending / drag til bryst','4 reps (2 RIR)','','Runde 1 · Start fra hofte, eksplosiv avslutning'),
('tif_offseason_3_v1','Main',3,1,'Valgfri bøy variant','4 reps @ 75–80 % (2 RIR)','','Runde 1 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v1','Main',4,1,'Step Up m/ manualer','6 reps per fot (2 RIR)','','Runde 1 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v1','Main',5,1,'Benkpress','4 reps 80–85 % benk','','Runde 1 · Prøv å være så eksplosiv som mulig opp'),
('tif_offseason_3_v1','Main',6,1,'Pull Ups / Nedtrekk','6 reps (2 RIR)','','Runde 1 · Full bevegelse, trekk albuer ned mot hofte'),
('tif_offseason_3_v1','Main',7,1,'Medball side kast','4 per side','','Runde 1 · Eksplosive kast med medisinball'),
('tif_offseason_3_v1','Main',8,1,'Copenhagen Plank','30s per side','','Runde 1 · Stabilisering kjerne'),
('tif_offseason_3_v1','Main',9,2,'Lateral Bound','4 per side','','Runde 2 · Sideveis eksplosivitet'),
('tif_offseason_3_v1','Main',10,2,'Frivending / drag til bryst','4 reps (2 RIR)','','Runde 2 · Start fra hofte, eksplosiv avslutning'),
('tif_offseason_3_v1','Main',11,2,'Valgfri bøy variant','4 reps @ 75–80 % (2 RIR)','','Runde 2 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v1','Main',12,2,'Step Up m/ manualer','6 reps per fot (2 RIR)','','Runde 2 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v1','Main',13,2,'Benkpress','4 reps 80–85 % benk','','Runde 2 · Prøv å være så eksplosiv som mulig opp'),
('tif_offseason_3_v1','Main',14,2,'Pull Ups / Nedtrekk','6 reps (2 RIR)','','Runde 2 · Full bevegelse, trekk albuer ned mot hofte'),
('tif_offseason_3_v1','Main',15,2,'Medball side kast','4 per side','','Runde 2 · Eksplosive kast med medisinball'),
('tif_offseason_3_v1','Main',16,2,'Copenhagen Plank','30s per side','','Runde 2 · Stabilisering kjerne'),
('tif_offseason_3_v1','Main',17,3,'Lateral Bound','4 per side','','Runde 3 · Sideveis eksplosivitet'),
('tif_offseason_3_v1','Main',18,3,'Frivending / drag til bryst','4 reps (2 RIR)','','Runde 3 · Start fra hofte, eksplosiv avslutning'),
('tif_offseason_3_v1','Main',19,3,'Valgfri bøy variant','4 reps @ 75–80 % (2 RIR)','','Runde 3 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v1','Main',20,3,'Step Up m/ manualer','6 reps per fot (2 RIR)','','Runde 3 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v1','Main',21,3,'Benkpress','4 reps 80–85 % benk','','Runde 3 · Prøv å være så eksplosiv som mulig opp'),
('tif_offseason_3_v1','Main',22,3,'Pull Ups / Nedtrekk','6 reps (2 RIR)','','Runde 3 · Full bevegelse, trekk albuer ned mot hofte'),
('tif_offseason_3_v1','Main',23,3,'Medball side kast','4 per side','','Runde 3 · Eksplosive kast med medisinball'),
('tif_offseason_3_v1','Main',24,3,'Copenhagen Plank','30s per side','','Runde 3 · Stabilisering kjerne'),
('tif_offseason_3_v1','Main',25,4,'Frivending / drag til bryst','4 reps (2 RIR)','','Runde 4 · Start fra hofte, eksplosiv avslutning'),
('tif_offseason_3_v1','Main',26,4,'Valgfri bøy variant','4 reps @ 75–80 % (2 RIR)','','Runde 4 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v1','Main',27,4,'Step Up m/ manualer','6 reps per fot (2 RIR)','','Runde 4 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v1','Main',28,4,'Benkpress','4 reps 80–85 % benk','','Runde 4 · Prøv å være så eksplosiv som mulig opp'),
('tif_offseason_3_v1','Main',29,4,'Pull Ups / Nedtrekk','6 reps (2 RIR)','','Runde 4 · Full bevegelse, trekk albuer ned mot hofte'),
('tif_offseason_3_v2','Main',1,1,'Lateral Bound','4 per side','','Runde 1 · Sideveis eksplosivitet'),
('tif_offseason_3_v2','Main',2,1,'Frivending / drag til bryst','3 reps (2 RIR)','','Runde 1 · Start fra hofte, eksplosiv avslutning'),
('tif_offseason_3_v2','Main',3,1,'Valgfri bøy variant','4 reps @ 75–80 % (2 RIR)','','Runde 1 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v2','Main',4,1,'Step Up m/ manualer','6 reps per fot (2 RIR)','','Runde 1 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v2','Main',5,1,'Explosive Bench Press','4 reps 40–50 % benk','','Runde 1 · Maks stanghastighet'),
('tif_offseason_3_v2','Main',6,1,'Pull Ups / Nedtrekk','6 reps (2 RIR)','','Runde 1 · Full bevegelse, trekk albuer ned mot hofte'),
('tif_offseason_3_v2','Main',7,1,'Sideplanke med rotasjon','8 reps per side','','Runde 1 · Stabilisering kjerne, kontrollert rotasjon'),
('tif_offseason_3_v2','Main',8,1,'Copenhagen Plank','30s per side','','Runde 1 · Stabilisering kjerne'),
('tif_offseason_3_v2','Main',9,2,'Lateral Bound','4 per side','','Runde 2 · Sideveis eksplosivitet'),
('tif_offseason_3_v2','Main',10,2,'Frivending / drag til bryst','3 reps (2 RIR)','','Runde 2 · Start fra hofte, eksplosiv avslutning'),
('tif_offseason_3_v2','Main',11,2,'Valgfri bøy variant','4 reps @ 75–80 % (2 RIR)','','Runde 2 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v2','Main',12,2,'Step Up m/ manualer','6 reps per fot (2 RIR)','','Runde 2 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v2','Main',13,2,'Explosive Bench Press','4 reps 40–50 % benk','','Runde 2 · Maks stanghastighet'),
('tif_offseason_3_v2','Main',14,2,'Pull Ups / Nedtrekk','6 reps (2 RIR)','','Runde 2 · Full bevegelse, trekk albuer ned mot hofte'),
('tif_offseason_3_v2','Main',15,2,'Sideplanke med rotasjon','8 reps per side','','Runde 2 · Stabilisering kjerne, kontrollert rotasjon'),
('tif_offseason_3_v2','Main',16,2,'Copenhagen Plank','30s per side','','Runde 2 · Stabilisering kjerne'),
('tif_offseason_3_v2','Main',17,3,'Lateral Bound','4 per side','','Runde 3 · Sideveis eksplosivitet'),
('tif_offseason_3_v2','Main',18,3,'Frivending / drag til bryst','3 reps (2 RIR)','','Runde 3 · Start fra hofte, eksplosiv avslutning'),
('tif_offseason_3_v2','Main',19,3,'Valgfri bøy variant','4 reps @ 75–80 % (2 RIR)','','Runde 3 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v2','Main',20,3,'Step Up m/ manualer','6 reps per fot (2 RIR)','','Runde 3 · Eksplosivt opp, kontrollert ned'),
('tif_offseason_3_v2','Main',21,3,'Explosive Bench Press','4 reps 40–50 % benk','','Runde 3 · Maks stanghastighet'),
('tif_offseason_3_v2','Main',22,3,'Pull Ups / Nedtrekk','6 reps (2 RIR)','','Runde 3 · Full bevegelse, trekk albuer ned mot hofte'),
('tif_offseason_3_v2','Main',23,3,'Sideplanke med rotasjon','8 reps per side','','Runde 3 · Stabilisering kjerne, kontrollert rotasjon'),
('tif_offseason_3_v2','Main',24,3,'Copenhagen Plank','30s per side','','Runde 3 · Stabilisering kjerne'),
('tif_offseason_3_v2','Main',25,4,'Frivending / drag til bryst','3 reps (2 RIR)','','Runde 4 · Start fra hofte, eksplosiv avslutning'),
('tif_offseason_3_v2','Main',26,4,'Explosive Bench Press','4 reps 40–50 % benk','','Runde 4 · Maks stanghastighet');

notify pgrst, 'reload schema';

select p.id,p.name,count(a.*) as activities
from public.cr_programs p
left join public.cr_program_activities a on a.program_id=p.id
where p.id in ('tif_offseason_1_v1','tif_offseason_1_v2','tif_offseason_2_v1','tif_offseason_2_v2','tif_offseason_3_v1','tif_offseason_3_v2')
group by p.id,p.name
order by p.sort_order;
